
kind: secret
name: mysql_user
---
kind: secret
name: mysql_password
---
kind: secret
name: sonar_url
---
kind: secret
name: sonar_project_token
---
kind: pipeline
type: docker
name: Test

steps:
- name: Run test
  image: maven:3.6.3-jdk-11
  environment:
    MYSQL_USER:
      from_secret:
        mysql_user
    MYSQL_PASSWORD:
      from_secret:
        mysql_password
  commands:
  - mvn test

- name: Sonar Scanner
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_token:
      from_secret: sonar_project_token
  enviroment:
    SONAR_URL:
      from_secret: sonar_url


trigger:
  branch:
    - master
