spring:
  application:
    name: timelog
  server:
    port: 9090
  data:
    mongodb:
      host: ${MONGODB_HOST:ssl-timelog.csie.ntut.edu.tw}
      port: ${MONGODB_PORT:27017}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWD}
      database: ${MONGO_DB:timelog}
