apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelog_v2_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timelog_v2_server
  template:
    metadata:
      labels:
        app: timelog_v2_server
    spec:
      containers:
        - name: timelog_v2_server
          image: nightlord851108/timelog_server
          imagePullPolicy: Always
          ports:
            - name: timelog_server-http
              containerPort: 9000
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: MYSQL_HOST
                  name: timelog-server-env-production
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: timelog-server-env-production
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: timelog-server-env-production
            - name: TIMELOG_MYSQL_DB
              valueFrom:
                secretKeyRef:
                  key: TIMELOG_MYSQL_DB
                  name: timelog-server-env-production
